#!/bin/sh
#
# Copyright (C) 2014 Stratio (http://stratio.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


#RPM

set -e

GROUP='stratio'
USER='decision'
DIR_INSTALL='/opt/sds/decision'
DIR_CONF='/etc/sds/decision'
DIR_LOG='/var/log/sds/decision'

# Add stratio group if it doesn't already exists
if ! getent group $GROUP >/dev/null 2>&1; then
groupadd ${GROUP}
fi

# Add stratio user if it doesn't already exists
if ! getent passwd $USER >/dev/null 2>&1; then
[ -d /opt ] || mkdir /opt
useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
else
usermod -G $GROUP $USER
fi

if [ ! -d "$DIR_LOG" ]; then
mkdir $DIR_LOG
fi

chown root:root /etc/init.d/decision

chown -R ${USER}:${GROUP} $DIR_INSTALL
chown -R ${USER}:${GROUP} /opt/sds/.m2

chown -R ${USER}:${GROUP} $DIR_CONF
chown -R ${USER}:${GROUP} $DIR_LOG


chmod 755 /etc/init.d/decision
chmod 755 /opt/sds/decision/bin/run
chmod 644 /etc/default/decision-functions
chmod 644 /etc/default/decision-variables

sed -i 's!"$BASEDIR"/:/etc/sds/decision/conf!/etc/sds/decision!g' /opt/sds/decision/bin/run

/sbin/chkconfig --add decision

exit 0