#!/bin/sh

#RPM

set -e

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/streaming'
DIR_CONF='/etc/sds/streaming'
DIR_LOG='/var/log/sds/streaming'
DIR_RUN='/var/run/sds'

# Add stratio group if it doesn't already exists
if ! getent group $GROUP >/dev/null 2>&1; then
groupadd ${GROUP}
fi

# Add stratio user if it doesn't already exists
if ! getent passwd $USER >/dev/null 2>&1; then
[ -d /opt ] || mkdir /opt
useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
else
usermod -G $GROUP $USER
fi

if [ ! -d "$DIR_LOG" ]; then
mkdir $DIR_LOG
fi

chown root:root /etc/init.d/streaming

chown -R ${USER}:${GROUP} $DIR_INSTALL

chown -R ${USER}:${GROUP} $DIR_CONF
chown -R ${USER}:${GROUP} $DIR_LOG
chmod -R 775 $DIR_INSTALL
chmod 775 $DIR_LOG

chown -R ${USER}:${GROUP} $DIR_RUN

chmod 755 /etc/init.d/streaming
chmod 755 /opt/sds/streaming/bin/run
chmod +x /etc/default/streaming

sed -i 's!"$BASEDIR"/:/etc/sds/streaming/conf!/etc/sds/streaming!g' /opt/sds/streaming/bin/run

/sbin/chkconfig --add streaming

exit 0