#!/bin/sh
# Copyright (c) 2016 Stratio (http://stratio.com)
#

set -e

GROUP='stratio'
USER='decision'
DIR_INSTALL='/opt/sds/decision-shell'

chmod 0755 /opt/sds/decision-shell/bin/*
chown -R $USER:$GROUP $DIR_INSTALL