# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "10.10.10.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    vb.gui = false
    vb.cpus = 2
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  
  # View the documentation for the provider you're using for more
  # information on available options.

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  $initScript = <<SCRIPT
echo -e '\e[1;34m    _____ __             __  _          _____ __                            _             '
echo -e '\e[1;34m   / ___// /__________ _/ /_(_)___     / ___// /_________  ____ _____ ___  (_)___  ____ _ '
echo -e '\e[1;34m   \\__ \\/ __/ ___/ __ `/ __/ / __ \\    \\__ \\/ __/ ___/ _ \\/ __ `/ __ `__ \\/ / __ \\/ __ `/ '
echo -e '\e[1;34m  ___/ / /_/ /  / /_/ / /_/ / /_/ /   ___/ / /_/ /  /  __/ /_/ / / / / / / / / / / /_/ /  '
echo -e '\e[1;34m /____/\\__/_/   \\__,_/\\__/_/\\____/   /____/\\__/_/   \\___/\\__,_/_/ /_/ /_/_/_/ /_/\\__, /   '
echo -e '\e[1;34m                                                                                /____/    '
echo -e ''

echo -e '\e[1;34mDownloading dependencies...'

add-apt-repository 'deb http://prerepository.stratio.com/TEST/0.9.2/ubuntu/13.10/ binary/'
add-apt-repository ppa:webupd8team/java

apt-get update -q -y

echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

apt-get install oracle-java7-installer oracle-java7-set-default -q -y

update-java-alternatives -s java-7-oracle

apt-get install stratio-kafka stratio-zookeeper stratio-cassandra -q -y --force-yes

update-rc.d kafka defaults
update-rc.d zookeeper defaults

service kafka start
service zookeeper start

echo -e '\e[1;34mDownloading stratio streaming...'
wget 'https://s3.amazonaws.com/stratioorg/streaming-engine-0.4.0-app.tar.gz'

echo -e '\e[1;34mUncompressing stratio streaming...'
tar -xzf streaming-engine-0.4.0-app.tar.gz

echo -e '\e[1;34mAdding privileges to vagrant user...'
chown -R vagrant:vagrant streaming-0.4.0
sudo -H -u vagrant bash -c 'mv -f streaming-0.4.0 ~'
sudo -H -u vagrant bash -c 'mv -f streaming-0.4.0 streaming'

echo -e '\e[1;34mRunning stratio streaming...'

mkdir -p /var/log/stratio
chown -R vagrant:vagrant /var/log/stratio

echo 'respawn
    respawn limit 15 5
    start on filesystem and net-device-up IFACE=lo
    exec /home/vagrant/streaming/bin/run >> /var/log/stratio/out' >> /etc/init/stratio-streaming.conf

update-rc.d stratio-streaming defaults

service stratio-streaming start

echo -e '\e[1;34mStratio streaming started!'

SCRIPT

  config.vm.provision "shell" do |s|
    s.inline = $initScript
    s.keep_color = true
  end

  # Enable provisioning with CFEngine. CFEngine Community packages are
  # automatically installed. For example, configure the host as a
  # policy server and optionally a policy file to run:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.am_policy_hub = true
  #   # cf.run_file = "motd.cf"
  # end
  #
  # You can also configure and bootstrap a client to an existing
  # policy server:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.policy_server_address = "10.0.2.15"
  # end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
  # config.vm.provision "puppet" do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "default.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision "chef_solo" do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { mysql_password: "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision "chef_client" do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
